[package]
name = "smoothie"
version = "0.1.0"
authors = ["Jason Murphy <json.murphy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
